### ISSUE TITLE
Fails to parse integer value on select systems

### ISSUE THREAD

**Issue by theRKF** [Bertware/wlan10#3]
I've downloaded the app, but it will not execute - just a blink of the screen as if an app is trying to load, but crashing.

Is it possible this isn't compatible with the latest version of Win10?

**Comment by Bertware** [comment]
Hmm, I don't have windows 10 anniversary (yet), but I can't imagine what would break. The netshell commands seems like something they won't change in a relative small update (it's not the same change as win7 > win8 for example). It relies on .NET 4.5 or .NET 4.6 (don't know from the top of my head),  but both of these should ship with windows 10. Did it run at the same computer before the update?

You could try downloading the drag&drop framework DLL from (here)[https://github.com/Bertware/wlan10/raw/master/Wlan10/Resources/GongSolutions.Wpf.DragDrop.dll] and putting it in the same folder as the application. This would resolve any problems with the embedded resources.

**Comment by theRKF** [comment]
Still no joy, sorry. I did notice that the first time I run the app the Windows location icon appears for a moment.

Might just be our system.

**Comment by akjohnston** [comment]
Hi,
I'm having exactly the same problem. My machine is patched up to date, so will have the anniversary updates.
Thanks
Andrew

**Comment by Bertware** [comment]
I upgraded my computer to windows 10 anniversary. I ran a version compiled from the sources, which worked fine. I also ran the version that's up for download here (release 1.1). Both versions ran fine.
The app works fine on both my desktop and laptop with different network adapters and different windows 10 versions.

Can you please try the following:
Open a command prompt (using Windows+r, type cmd, hit enter).
In the command prompt, enter "netsh wlan sh profiles" without the "". The resulting text should be     similar to this:

    Profiles on interface Wi-Fi:
    
    Group policy profiles (read only)
    ---------------------------------
        <None>
    
    User profiles
    -------------
        All User Profile     : Wifi-name
        All User Profile     : other wifi network

If the output is different, or the command does not work, please post back with the result you get.

If the above does not work, please try running this debug build. I added a few lines of code to put any error that occurs into a messagebox. If you see an error with this build, please either copy-paste all information, or post a screenshot.
[debug-wlan10-1-1-0.zip](https://github.com/Bertware/wlan10/files/440271/debug-wlan10-1-1-0.zip)

I hope this information will allow me to resolve the issue, thanks for the feedback already!

**Comment by akjohnston** [comment]
Hi
It still doesn't work, but I think I should have produced enough output for you to see what's happening. Please find attached error screenshot + list of my profiles. You'll see that there are a lot of them, and some have names which include punctuation etc.

Thanks
Andrew 
![wlan10 error](https://cloud.githubusercontent.com/assets/21262696/18029874/6b561d4e-6c9c-11e6-807d-928f2c09383d.jpg)
[profiles.txt](https://github.com/Bertware/wlan10/files/440837/profiles.txt)

**Comment by Bertware** [comment]
Thanks a lot! This clears up a lot, probably one of the profile parameters has a special value in your case.
It looks like some of microsoft's documentation was incomplete. Can you please run this build? It will allow you to load the recognized networks, and it will show complete debug output for unrecognized networks. This way I can see which value is wrong (it might be a single network, and there are 3 possible bad values, so this is the easiest way to find the bug)
Please run, and upload a screenshot of the error message.

[Wlan10-debug-1.1.1.zip](https://github.com/Bertware/wlan10/files/440868/Wlan10-debug-1.1.1.zip)

Thanks a lot already, your information is great at tracing the issue!

**Comment by theRKF** [comment]
Thanks for tackling this!

Using 1.1.1 it output a few errors (error, crash, relaunch, error, error, loads & works) then worked well. Errors are attached for your review.
![wlan error 2](https://cloud.githubusercontent.com/assets/4484547/18031021/ae44defc-6c9b-11e6-8038-3c82acb6a4ff.PNG)
![wlan error 3](https://cloud.githubusercontent.com/assets/4484547/18031023/ae4e9294-6c9b-11e6-87de-7905ca16261c.PNG)
![wlan error](https://cloud.githubusercontent.com/assets/4484547/18031022/ae4c4e8a-6c9b-11e6-8411-b159b2460ec1.PNG)

**Comment by akjohnston** [comment]
Hi,
Here's screen shot from my system at start-up. Otherwise it seems to work well.
Thanks
Andrew
![wlan10 error](https://cloud.githubusercontent.com/assets/21262696/18031931/c4ec8906-6cec-11e6-9158-b8b18bc11b4e.jpg)

**Comment by Bertware** [comment]
Thanks to the screenshots and the attached profiles file, I was able to both reproduce and fix all issues. Thanks a lot for those, they really made debugging a lot easier. There are a few field values that were unexpected (values that never occurred on my computers) causing some havoc in the model.
Anyway, all issues should be resolved now, and the dialog should not popup any longer.

The new binary can be downloaded from this release:
https://github.com/Bertware/wlan10/releases/tag/1.1.2
